version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
  #    environment:
  #      SERVER_NAME: kibana.example.org
  #      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - ELASTIC_PASSWORD=cqx534
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - host

volumes:
  esdata1:
    driver: local
networks:
  esnet: bridge
