version: '2'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    depends_on:
      - elasticsearch  
    ports:
      - 5000:5000
      - 5044:5044
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - ELASTIC_PASSWORD=abcdefg
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.2
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /root/repo/elk/logstash-tutorial.log:/usr/share/filebeat/logstash-tutorial.log
    depends_on:
      - logstash
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
networks:
  esnet:
    driver: bridge
