version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
#      volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://127.0.0.1:9200
    depends_on:
      - elasticsearch
    networks:
      - host   
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - host

volumes:
  esdata1:
    driver: local
networks:
  host: 
